### ISSUE TITLE
Create service to generate css classes dynamically based on keywords

### ISSUE THREAD

**Issue by doomsayer2** [fhstp/highlighter-webapp#10]
Dynamically generate css classes based on keywords in order to highlight the appropriate words.

**Comment by alex-rind** [comment]
https://github.com/d3/d3-scale-chromatic#schemeSet3 
I recommend established color scheme over interpolation in color space.

**Comment by doomsayer2** [comment]
A good idea, however the HSV conversion has 2 major advantages like it's built at the moment. If not 3 advantages:
1) Full control over the colors and save them global
2) Much faster code than using a full powered library
**3) If we want to change the text color to white or black based on bright or dark colors we need HSV values. Because . if V is above (light) 75% or below (dark) 25%.**
